name: spectrogram_editor
description: A real-time spectrogram editor with GPU-accelerated processing
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  material_color_utilities: ^0.5.0
  
  # Platform integration
  plugin_platform_interface: ^2.1.0
  
  # File operations
  file_picker: ^5.3.0
  path_provider: ^2.1.0
  
  # State management
  provider: ^6.0.5
  
  # Audio processing
  audio_players: ^0.20.1
  
  # Networking for DSP service communication
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  
  # Math and utilities
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Fragment shader assets
  shaders:
    - shaders/blur.frag
    - shaders/warp.frag
    - shaders/texture.vert
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

# Platform-specific configurations
flutter_native_splash:
  color: "#1e1e1e"
  image: "assets/images/splash_logo.png"
  android: false
  ios: false
  web: false